# Generated by Django 2.2 on 2021-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_aquisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperorayProductivityTable',
            fields=[
                ('Date', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ALUMSK', models.FloatField()),
                ('SH', models.FloatField()),
                ('SC', models.FloatField()),
                ('SCR', models.FloatField()),
            ],
        ),
    ]
