# Generated by Django 2.2 on 2022-01-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_aquisition', '0002_temperorayproductivitytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceCncFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pers_No', models.CharField(max_length=50, null=True)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('CC', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100)),
                ('Attendance_Time', models.FloatField(null=True)),
                ('Date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AttendanceCNCPerson', to='Data_aquisition.DimDate', to_field='StartDateKey')),
            ],
            options={
                'unique_together': {('Pers_No', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceAssFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pers_No', models.CharField(max_length=50, null=True)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('CC', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100)),
                ('Attendance_Time', models.FloatField(null=True)),
                ('Date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AttendancePerson', to='Data_aquisition.DimDate', to_field='StartDateKey')),
            ],
            options={
                'unique_together': {('Pers_No', 'Date')},
            },
        ),
    ]
