# Generated by Django 2.2 on 2022-01-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_aquisition', '0003_dailyattendanceassfact_dailyattendancecncfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlineattendancefact',
            name='Date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='AttendanceAssPerson', to='Data_aquisition.DimDate', to_field='StartDateKey', unique=True),
        ),
    ]
